
// Objective-C API for talking to the following Go packages
//
//	github.com/tladesignz/IPtProxy.git
//
// File is generated by gomobile bind. Do not edit.
#ifndef __IPtProxy_FRAMEWORK_H__
#define __IPtProxy_FRAMEWORK_H__

#include "IPtProxy.objc.h"
#include "Universe.objc.h"

#endif
